-- ============================================================
--  مراح — استكمال الجداول الناقصة التي يعتمد عليها التطبيق:
--    mrahi_settings : إعدادات عامة (فتح/إغلاق التسجيل + إعدادات المنتدى)
--    mrahi_types    : أنواع الحلال القابلة للإدارة من المدير
--    mrahi_trash    : سلة المحذوفات/الأرشيف + دالة تنظيف تلقائي
--  نفّذه بعد بقية السكربتات. آمن للتكرار.
-- ============================================================

-- ---------- 1) الإعدادات العامة ----------
create table if not exists public.mrahi_settings (
  key        text primary key,
  value      jsonb,
  updated_at timestamptz not null default now()
);
alter table public.mrahi_settings enable row level security;

-- القراءة متاحة للجميع (تُقرأ قبل تسجيل الدخول لتحديد فتح/إغلاق التسجيل)
drop policy if exists settings_sel on public.mrahi_settings;
create policy settings_sel on public.mrahi_settings for select using (true);
-- الكتابة للمدير فقط
drop policy if exists settings_ins on public.mrahi_settings;
create policy settings_ins on public.mrahi_settings for insert with check (public.mrahi_is_admin());
drop policy if exists settings_upd on public.mrahi_settings;
create policy settings_upd on public.mrahi_settings for update using (public.mrahi_is_admin()) with check (public.mrahi_is_admin());
drop policy if exists settings_del on public.mrahi_settings;
create policy settings_del on public.mrahi_settings for delete using (public.mrahi_is_admin());

-- ---------- 2) أنواع الحلال ----------
create table if not exists public.mrahi_types (
  id   bigint generated by default as identity primary key,
  key  text not null,
  ar   text not null,
  gest integer not null default 150,
  sort integer not null default 0
);
alter table public.mrahi_types enable row level security;

drop policy if exists types_sel on public.mrahi_types;
create policy types_sel on public.mrahi_types for select using (public.mrahi_is_member());
drop policy if exists types_ins on public.mrahi_types;
create policy types_ins on public.mrahi_types for insert with check (public.mrahi_is_admin());
drop policy if exists types_upd on public.mrahi_types;
create policy types_upd on public.mrahi_types for update using (public.mrahi_is_admin()) with check (public.mrahi_is_admin());
drop policy if exists types_del on public.mrahi_types;
create policy types_del on public.mrahi_types for delete using (public.mrahi_is_admin());

-- بذور افتراضية (آمنة للتكرار) — تطابق القائمة المضمّنة في التطبيق
insert into public.mrahi_types (key, ar, gest, sort) values
  ('camel','إبل',390,10),
  ('sheep','غنم',150,20),
  ('goat','ماعز',150,30),
  ('cattle','بقر',283,40)
on conflict do nothing;

-- ---------- 3) سلة المحذوفات / الأرشيف ----------
create table if not exists public.mrahi_trash (
  id         bigint generated by default as identity primary key,
  owner_id   uuid not null default auth.uid(),
  tbl        text not null,
  rec_id     bigint,
  action     text,
  label      text,
  data       jsonb,
  actor_name text default '',
  created_at timestamptz not null default now()
);
alter table public.mrahi_trash enable row level security;
create index if not exists mrahi_trash_owner_idx on public.mrahi_trash(owner_id, created_at desc);

-- كل مستخدم يرى/يدير محذوفاته؛ والمدير يرى الكل
drop policy if exists trash_sel on public.mrahi_trash;
create policy trash_sel on public.mrahi_trash for select using (owner_id = auth.uid() or public.mrahi_is_admin());
drop policy if exists trash_ins on public.mrahi_trash;
create policy trash_ins on public.mrahi_trash for insert with check (owner_id = auth.uid());
drop policy if exists trash_del on public.mrahi_trash;
create policy trash_del on public.mrahi_trash for delete using (owner_id = auth.uid() or public.mrahi_is_admin());

-- دالة تنظيف العناصر الأقدم من 30 يوماً (تُستدعى تلقائياً عند تحميل التطبيق)
create or replace function public.mrahi_purge_trash() returns void
  language sql security definer set search_path = public as $$
  delete from public.mrahi_trash where created_at < now() - interval '30 days';
$$;
